name: forward_chaining_man_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  cloud_firestore: ^5.6.4
  data_table_2: 2.5.16
  firebase_auth: ^5.5.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_svg: ^2.0.17
  get: ^4.6.6
  google_sign_in: ^6.2.2
  intl: ^0.20.2
  lottie: ^3.2.0
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  image_gallery_saver_plus: ^4.0.1
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/