// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLw5Y3FPYwfij3VfTDOciRFukzpki9gYk',
    appId: '1:1072369607324:web:d17906f3452e68cb6f4359',
    messagingSenderId: '1072369607324',
    projectId: 'sirekomendasi-dc7de',
    authDomain: 'sirekomendasi-dc7de.firebaseapp.com',
    storageBucket: 'sirekomendasi-dc7de.firebasestorage.app',
    measurementId: 'G-V7MND9NDT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIHdD_rH3YSfuZYcNKFd1YCMTXxYb6gdc',
    appId: '1:1072369607324:android:ed7767d8870c32e96f4359',
    messagingSenderId: '1072369607324',
    projectId: 'sirekomendasi-dc7de',
    storageBucket: 'sirekomendasi-dc7de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI7KTuPhqGiIkX5pznUDYkToUmIhznqf8',
    appId: '1:1072369607324:ios:1d8cb1dbadb289ff6f4359',
    messagingSenderId: '1072369607324',
    projectId: 'sirekomendasi-dc7de',
    storageBucket: 'sirekomendasi-dc7de.firebasestorage.app',
    iosClientId: '1072369607324-0e0k7pn3nqk6suq97jnegljp3k0161o5.apps.googleusercontent.com',
    iosBundleId: 'com.example.forwardChainingManApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI7KTuPhqGiIkX5pznUDYkToUmIhznqf8',
    appId: '1:1072369607324:ios:1d8cb1dbadb289ff6f4359',
    messagingSenderId: '1072369607324',
    projectId: 'sirekomendasi-dc7de',
    storageBucket: 'sirekomendasi-dc7de.firebasestorage.app',
    iosClientId: '1072369607324-0e0k7pn3nqk6suq97jnegljp3k0161o5.apps.googleusercontent.com',
    iosBundleId: 'com.example.forwardChainingManApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLw5Y3FPYwfij3VfTDOciRFukzpki9gYk',
    appId: '1:1072369607324:web:7c9de102a40074a66f4359',
    messagingSenderId: '1072369607324',
    projectId: 'sirekomendasi-dc7de',
    authDomain: 'sirekomendasi-dc7de.firebaseapp.com',
    storageBucket: 'sirekomendasi-dc7de.firebasestorage.app',
    measurementId: 'G-4JLGBJVJBM',
  );
}
